/**
 * @file gen-mod-tests.ts
 * @description Generates one vitest file per mod from _test/all_mods.json.
 *
 * Each generated file runs in its own Vitest worker process, isolating
 * memory usage so that only a single CBNData instance exists at a time.
 * This avoids the OOM errors caused by accumulating all mod instances
 * when tests are grouped in chunk files.
 *
 * Generated files are gitignored and must be regenerated before running
 * the full test suite (pnpm test:full does this automatically).
 *
 * @usage
 * ```bash
 * pnpm gen:mod-tests
 * ```
 */

import * as fs from "fs/promises";
import * as path from "path";
import * as url from "url";

const __dirname = url.fileURLToPath(new URL(".", import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const modsJsonPath = path.join(projectRoot, "_test", "all_mods.json");
const outDir = path.join(projectRoot, "src", "__mod_tests__");

const FILE_HEADER = `/**
 * @vitest-environment happy-dom
 * Auto-generated by scripts/gen-mod-tests.ts — do not edit manually.
 * Regenerated on every \`pnpm gen:mod-tests\` / \`pnpm test:full\` run.
 */`;

async function main(): Promise<void> {
  const raw = await fs.readFile(modsJsonPath, "utf8");
  const modsJson = JSON.parse(raw) as Record<string, unknown>;

  const modIds = Object.keys(modsJson).filter(
    (id: string): boolean =>
      modsJson[id] != null &&
      typeof modsJson[id] === "object" &&
      Array.isArray((modsJson[id] as Record<string, unknown>).data),
  );

  await fs.mkdir(outDir, { recursive: true });

  // Remove stale generated files before writing fresh ones
  const existing = await fs.readdir(outDir);
  await Promise.all(
    existing
      .filter((f: string): boolean => f.endsWith(".test.ts"))
      .map((f: string): Promise<void> => fs.unlink(path.join(outDir, f))),
  );

  await Promise.all(
    modIds.map((modId: string): Promise<void> => {
      // Escape the modId for safe embedding in a string literal.
      // Mod IDs in CBN are simple ASCII identifiers, but be safe.
      const escaped = JSON.stringify(modId);
      const content = [
        FILE_HEADER,
        ``,
        `import { makeModRenderTests } from "../testRenderMods";`,
        ``,
        `makeModRenderTests(${escaped});`,
        ``,
      ].join("\n");

      const filename = `mod.${modId}.test.ts`;
      return fs.writeFile(path.join(outDir, filename), content, "utf8");
    }),
  );

  console.log(
    `Generated ${modIds.length} mod test files in src/__mod_tests__/`,
  );
}

main().catch((err: unknown): void => {
  console.error("gen-mod-tests failed:", err);
  process.exit(1);
});
