name: Run Tests
permissions:
  contents: read

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
  schedule:
    - cron: "55 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # Run scheduled tests on the latest version of the game, on push - on commited in all.meta.json
      - name: Fetch fixtures
        run: |
          pnpm fetch:builds
          if [ "$GITHUB_EVENT_NAME" == "schedule" ]; then
            pnpm fetch:fixtures:nightly
          else
            pnpm fetch:fixtures
          fi

      - name: Verify & Test
        run: pnpm test

      - name: Build
        run: pnpm build
